version: 1.0.{build}
build:
  verbosity: minimal
image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

#build: off

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации